version: 2
workflows:
  version: 2
  test:
    jobs:
      - test-filenames

jobs:
  test-filenames:
    docker:
      - image: python:3.7-alpine
    steps:
      - checkout
      - run:
          name: Run filename test
          command: python verify_filenames.py   
